tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"
brew "bat"
brew "cmake"
brew "curl"
brew "diff-so-fancy"
brew "exa"
brew "fasd"
brew "fcitx-remote-for-osx"
brew "fzf"
brew "gcc"
brew "git"
brew "go"
brew "graphviz"
brew "htop"
brew "jq"
brew "make"
brew "mas"
brew "ncdu"
brew "neovim"
brew "pandoc"
brew "plantuml"
brew "prettyping"
brew "proxychains-ng"
brew "pyenv"
brew "rbenv"
brew "rustup-init"
brew "the_silver_searcher"
brew "thefuck"
brew "tmux"
brew "tree"
brew "vim"
brew "yarn"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "1password"
cask "alfred3"
cask "bartender"
cask "bettertouchtool"
cask "clashx"
cask "contexts"
cask "daisydisk"
cask "dash"
cask "default-folder-x"
cask "docker"
cask "dotnet"
cask "epic-games"
cask "expressions"
cask "folx"
cask "font-anonymouspro-nerd-font"
cask "font-firacode-nerd-font"
cask "font-hack-nerd-font"
cask "hazeover"
cask "iina"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "kindle"
cask "loginputmac"
cask "mosaic"
cask "mounty"
cask "mweb"
cask "neteasemusic"
cask "ogdesign-eagle"
cask "omnifocus"
cask "paw"
cask "shadowsocksx-ng-r"
cask "snipaste"
cask "steam"
cask "timing"
cask "visual-studio-code"
cask "vmware-fusion"
cask "xquartz"
mas "HazeOver", id: 430798174
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
